// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contacts/:contactId": {
    params: {
      "contactId": string;
    };
  };
  "/contacts/:contactId/edit": {
    params: {
      "contactId": string;
    };
  };
  "/contacts/:contactId/destroy": {
    params: {
      "contactId": string;
    };
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contacts/:contactId" | "/contacts/:contactId/edit" | "/contacts/:contactId/destroy" | "/about";
  };
  "layouts/sidebar.tsx": {
    id: "layouts/sidebar";
    page: "/" | "/contacts/:contactId" | "/contacts/:contactId/edit" | "/contacts/:contactId/destroy";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contacts/:contactId";
  };
  "routes/edit-contact.tsx": {
    id: "routes/edit-contact";
    page: "/contacts/:contactId/edit";
  };
  "routes/destroy-contact.tsx": {
    id: "routes/destroy-contact";
    page: "/contacts/:contactId/destroy";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/sidebar": typeof import("./app/layouts/sidebar.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/edit-contact": typeof import("./app/routes/edit-contact.tsx");
  "routes/destroy-contact": typeof import("./app/routes/destroy-contact.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
};